spring.application.name=api-gateway
server.port=9000

# URL cac service dich (co the doi theo moi truong, khong can sua code)
services.product.url=http://localhost:8080
services.order.url=http://localhost:8081
services.inventory.url=http://localhost:8082
